version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: pdf-viewer-frontend
    restart: unless-stopped
    ports:
      - "8002:80"
    networks:
      - pdf-viewer-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pdf-viewer-backend
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - PORT=5001
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - pdf-viewer-network

networks:
  pdf-viewer-network:
    driver: bridge 